### ISSUE TITLE
Not able to access any js, css files starting with /mms-ts

### ISSUE THREAD

**Issue by kalpesh15** [Open-MBEE/ve#128]
Hi I have just started using ve and mms.
Any resource files having mms-ts are not accessible. For example mms-ts/tspersepectives/TSWebView.css from mms.html.or is there any way around it?
Any help on this matter?

**Comment by dlamoris** [comment]
those are only for TomSawyer Perspectives visualization integration, which is not open sourced. It should have no adverse effects with them not being accessible
