### ISSUE TITLE
Initial Organization and Projects setup 

### ISSUE THREAD

**Issue by o7g8** [Open-MBEE/ve#155]
Hello,

I wonder what is the recommended tool to make the initial setup of the Organization and Projects?
I did it via Swagger UI, but I wonder if there is a UI/tool for this? 
The older pdf documentation refers to Alfresco, therefore I wonder if any Alfresco products are still needed as an UI tool to setup Organization and Projects?

**Comment by dlamoris** [comment]
Currently only mdk or using the api is the only way, Alfresco is no longer part of mms4. There are some plans to create an admin ui but no eta for that
