### ISSUE TITLE
"Tarball is not in network and can not be located in cache"

### ISSUE THREAD

**Issue by CampusClub** [Open-MBEE/ve#209]
When I use docker to deploy VE, my yarn cannot normally read `openmbee-angularjs-dropdown-multiselect-v1.0.2.tgz` in the local folder ./lib, and the error message shows:
`error "./lib/openmbee-angularjs-dropdown-multiselect-v1.0.2.tgz": Tarball is not in network and can not be located in cache (["/opt/mbee/ve/lib/openmbee-angularjs-dropdown -multiselect-v1.0.2.tgz","/usr/local/share/.cache/yarn/v6/npm-@openmbee-angularjs-dropdown-multiselect-1.0.2-d219ab5df1b76b2c1690b20df09119f7746973e3/node_modules/@openmbee/angul arjs-dropdown -multiselect/.yarn-tarball.tgz"])`
I've read almost all similar issues on Google. According to the information in these issues, it seems that there is a problem with the reference to the offline cache in the package.json and yarn.lock files, which results in the Tarball not passed to the docker instance.
For example, the reference record in the package.json file is:
`"@openmbee/angularjs-dropdown-multiselect": "./lib/openmbee-angularjs-dropdown-multiselect-v1.0.2.tgz"`
And The reference record in the yarn.lock file is:
`"@openmbee/angularjs-dropdown-multiselect@./lib/openmbee-angularjs-dropdown-multiselect-v1.0.2.tgz":
   version "1.0.2"
   resolved "./lib/openmbee-angularjs-dropdown-multiselect-v1.0.2.tgz#d219ab5df1b76b2c1690b20df09119f7746973e3"
   dependencies:
     angular "1.8.3"
     jquery "^3.6.0"
     lodash  #"^4.17.21"`
Refering to  [https://stackoverflow.com/questions/40102686/how-to-install-package-with-local-path-by-yarn-it-couldnt-find-package](url), [https://github.com/yarnpkg/yarn /issues/2861](url), [https://github.com/yarnpkg/yarn/issues/2920](url) and some other issues, I tried various repair methods, including modifying the path and resetting the cache, etc., but none of them could solve the problem .
I'm wondering if I understood the error correctly, or if this tarball file is corrupted. I've spent a long time to solve this problem, could anyone give me some help plz?

**Comment by sand7000** [comment]
They accidentally skipped adding the file to the WORKDIR. To fix add the line:

`!lib`

to .dockerignore

**Comment by CampusClub** [comment]
> They accidentally skipped adding the file to the WORKDIR. To fix add the line:
> 
> `!lib`
> 
> to .dockerignore

Thank you! I will try.
