### ISSUE TITLE
Update pdf location now that Documents folder exists

### ISSUE THREAD

**Issue by borromeotlhs** [Open-MBEE/ve#47]
https://github.com/Open-MBEE/ve/blob/develop/Documents/ViewEditorUserGuide.pdf Will be put into the markdown. Making this ticket to demarcate once I get to my work laptop.

**Comment by capsulecorplab** [comment]
URL in README.md redirects to 
https://github.com/Open-MBEE/ve/blob/opensource/Documents/ViewEditorUserGuide-OpenMBEE.pdf
instead of
https://github.com/Open-MBEE/ve/blob/develop/Documents/ViewEditorUserGuide.pdf

**Comment by borromeotlhs** [comment]
Moved to https://github.com/Open-MBEE/ve/tree/master so that the next develop downmerge/branch should fix it here?  It isn't an issue with the development branch, as documentation, to me, is a pre-development issue. . .
